---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by jesse.
--- DateTime: 2019-03-24 16:46
---


function main(splash, args)
    splash.images_enabled=false
    assert(splash:go(args.url))
    assert(splash:wait(0.5))
    return {
        png = splash:png(),
        html = splash:html(),
        har = splash:har(),
    }
end